services:
  naos-ventas-back:
    build:
      context: ./servidor
      dockerfile: Dockerfile
    image: naos-ventas-back
    ports:
      - 4000:4000  
    environment:
      - DB_Mongo=mongodb://mongo:27017/MeanSistemaVentas
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.35'  
          memory: 350M  
        reservations:
          cpus: '0.20'  
          memory: 250M  

  naos-ventas-front:
    build:
      context: ./SistemaVentas
      dockerfile: Dockerfile
    image: naos-ventas-front  
    ports:
      - 80:80 
    depends_on:
      - naos-ventas-back  
    deploy:
      resources:
        limits:
          cpus: '0.30'  
          memory: 300M  
        reservations:
          cpus: '0.15'  
          memory: 200M  

  mongo:
    image: mongo:4.4
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: MeanSistemaVentas
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./mongo-init/scripts:/docker-entrypoint-initdb.d/
      - ./mongo-init/datos:/docker-entrypoint-initdb.d/datos   # Montar la carpeta de datos en el contenedor
  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
        ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
        ME_CONFIG_BASICAUTH: false
      deploy:
        resources:
          limits:
            cpus: "0.3"
            memory: "128M"
          reservations:
            cpus: "0.1"
            memory: "64M"


  # Otros servicios aquí...

volumes:
  mongo_data:


